# Generated by Django 5.1.12 on 2025-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("hard", "Hard"),
                    ("severe", "Severe"),
                ],
                help_text="Overall route difficulty",
                max_length=10,
                null=True,
            ),
        ),
    ]
